// #define WF_DEBUG 1
#define WF_LOG_CONTENT
#define IS_CHERNARUS_MAP_DEPENDENT
//#define IS_MOD_MAP_DEPENDENT
#define IS_NAVAL_MAP
//#define IS_AIR_WAR_EVENT
#define WF_MAXPLAYERS 57
#define WF_MISSIONNAME "[55] Warfare V48 Chernarus-Pr0ph3tedits"
#define STARTING_DISTANCE 10000
#define COMBINEDOPS 1
#define WF_RESPAWNDELAY 2